bbc/genie

- themes/default/config/results.json5
https://jira.dev.bbc.co.uk/browse/CGPROD-2136
Added and claified some comments for helpful guidance.
> CGPROD-2136 JSON5 comment documentation

- themes/default/config/results.json5
> [NOTICKET] Added comment pointing to countup docs

- src/components/select/single-item-mode.js
- test/components/select/single-item-mode.test.js
Fixes tab loop on initial creation of page.
> Cgprod 2149 tabbing loop

- lib/crel.es.js
- package-lock.json
- package.json
- src/core/accessibility/accessibility-layer.js
- src/core/accessibility/accessible-dom-element.js
- src/main.js
Removes Proxy from crel as babel has no way to reliably polyfill it.
> CGPROD 2137 IE11 build issue

- src/core/loader/loadpack.js
overwrite defaults to false
https://jira.dev.bbc.co.uk/browse/CGPROD-2127
> CGPROD-2127 Remove redundant keys

- docs/development/code-restrictions.md
https://jira.dev.bbc.co.uk/browse/CGPROD-2128
> CGPROD-2128 Document world bounds

- src/components/select/single-item-mode.js
- test/components/select/single-item-mode.test.js
Fixes shift tabbing on final element in grid
> CGPROD 2156 - reverse tabbing

- src/components/select/select-screen.js
- src/components/select/titles.js
- test/components/select/select-screen.test.js
- test/components/select/titles.test.js
- themes/default/config/character-select.json5
Subtitle text aligns the same way as title text on the select screen.
> CGPROD-2157_Select-Subtitle-Text-Is-Aligned

- src/components/select/select-screen.js
- src/components/select/single-item-mode.js
- src/core/layout/button-factory.js
- src/core/layout/grid/grid.js
- src/core/layout/layout.js
- src/core/screen.js
- test/components/select/select-screen.test.js
- test/components/select/single-item-mode.test.js
- test/core/layout/button-factory.test.js
- test/core/layout/grid/grid.test.js
- test/core/layout/layout.test.js
- test/core/screen.test.js
- test/game.test.js
- themes/default/config/character-select.json5
* Remove all events created by single item mode on shutdown
* Call shutdown on overlay created
* Call single item mode on overlay closed
> Cgprod 2112 single item pause

- docs/development/select-screen.md
- themes/default/config/character-select.json5
adds choicesStyling for titles
Add JSON5 comments to select config
> CGPROD-2214  Docs update for select screen

- CHANGELOG.md
- src/components/select/select-screen.js
- src/components/select/titles.js
- src/core/layout/grid/cell.js
- src/core/screen.js
- test/components/select/select-screen.test.js
- test/components/select/titles.test.js
- test/core/layout/grid/cell.test.js
- test/core/screen.test.js
Adds assetPrefix to screen.js - enables prefix override in themes.
> NOTICKET asset prefix

- CHANGELOG.md
- README.md
- dev/docs/notes-on-genie-core.md
- dev/scripts/gmi.js
- docs/development/gameplay-component.md
- src/core/startup.js
- test/components/how-to-play.test.js
- test/core/parseUrlParams.test.js
- test/core/screen.test.js
Removes now defunct references to qamode and replaces them with debug = true.
> NOTICKET QA Mode

- lib/SpinePlugin.js
Remove sourcemap link from temporary spine plugin to prevent following warning:
"DevTools failed to parse SourceMap: http://localhost:8000/lib/spine-both.js.map"
> NOTICKET Sourcemaps

- CHANGELOG.md
- src/core/debug/debug.js
- test/core/debug/debug.test.js
- themes/default/config/home.json5
Changes debug description to debug labels array.
Allows multiple labels to be added for examples
> NOTICKET debug labels

- CHANGELOG.md
- package.json
- src/core/debug/debug.js
- test/core/debug/debug.test.js
* Fix crash when using debug mode layout has not been set.
* Fix crash when using debug mode and debug update is called before debug create.
> Fix debug mode crashes

- debug/examples/background-particles.json5
- src/core/background-furniture.js
- test/core/background-furniture.test.js
- themes/default/examples/particles/spray.json
* Copies custom properties to background particles if available
* Update example page
> Add custom props for background particles

- src/core/debug/examples.js
Made large score 1 million at request of QA.
> NOTICKET Example scores

- docs/development/particles.md
- src/core/loader/particles-loader/geom-parse.js
- src/core/loader/particles-loader/particles-file.js
- test/core/loader/particles-loader/geom-parse.test.js
- test/core/loader/particles-loader/particle-file.test.js
- themes/default/examples/particles/spray.json
just the geom parsing stuff in this PR
> [CGPROD-2204] Parse JSON into Phaser.Geoms

- CHANGELOG.md
- build-scripts/build.sh
- debug/examples/background-animations.json5
- debug/examples/background-particles.json5
- debug/examples/results-1-sec.json5
- debug/examples/results-10-sec.json5
- debug/examples/results-spine.json5
- debug/examples/select-1.json5
- debug/examples/select-grid.json5
> NOTICKET Example backdrop fixes

- src/components/game.js
Switch demo game to use assetPrefix: 
* Better example for agencies
* Useful for testing multi- component spikes
> NOTICKET assetPrefix on demo game

- src/core/game-sound.js
- src/core/screen.js
- test/core/game-sound.test.js
- test/core/screen.test.js
Removes unnecessary arg from game sound.
> Noticket game sound

- CHANGELOG.md
- UPGRADE-NOTES.md
- docs/development/gmi.md
- docs/development/select-screen.md
- docs/development/settings.md
- package.json
- src/core/accessibility/accessibility-layer.js
- src/core/loader/container.js
- src/core/loader/phaserDefaults.js
- src/core/startup.js
- src/main.js
- test/core/accessibility/accessibility-layer.test.js
- test/core/loader/container.test.js
- test/core/loader/phaserDefaults.test.js
- test/core/startup.test.js
- test/main.test.js
Splits phaser default config generation and adds ability to add basic game options from mian.js
> Noticket game options

- CHANGELOG.md
- debug/examples/results-1-sec.json5
- debug/examples/results-10-sec.json5
- debug/examples/results-row-particles.json5
- debug/examples/results-spine.json5
- src/components/results/results-row-backdrop.js
- test/components/results/results-row-backdrop.test.js
- themes/default/config/results.json5
Use only one alpha value for a result row.
> NOTICKET combine result alphas

- docs/development/results-screen/results-start.md
added doc entry for gameComplete transient data
> CGPROD-2405 Docs update

- CHANGELOG.md
- src/components/narrative.js
- src/core/layout/gel-defaults.js
- src/main.js
- test/components/narrative.test.js
> Cgprod 2417 narrative screen

- src/core/background/furniture.js
- src/core/background/image.js
- src/core/background/particles.js
- src/core/background/spine.js
- src/core/background/sprite.js
- src/core/background/text.js
- test/core/background/furniture.test.js
- themes/default/config/narrative.json5
* Adds names to background items for use by narrative animation system
> NOTICKET background item names

- CHANGELOG.md
- src/core/loader/loadpack.js
- themes/default/asset-packs/home.json
- themes/default/config/character-select.json5
- themes/default/config/home.json5
- themes/default/config/level-select.json5
- themes/default/config/narrative.json5
* Move background music out of loadpack.js and into asset master pack.
> NOTICKET Background Music

- src/core/background/items.js
- test/core/background/items.test.js
* Fix error when motion fx disabled.
> CGPROD 2500 Motion Fx Issue

- src/core/background/pages.js
- src/core/layout/gel-defaults.js
- test/core/layout/gel-defaults.test.js
* Force end animations and audio when the skip button is pressed.
> CGPROD 2499 Audio skip

- src/components/select/select-screen.js
- src/core/layout/grid/grid.js
- test/components/select/select-screen.test.js
- test/core/layout/grid/grid.test.js
* Disable next / previous buttons when only one page
> CGPROD 2480 Single Item Select

- CHANGELOG.md
- docs/development/narrative-screen.md
- docs/development/select-screen.md
- package-lock.json
- src/components/narrative.js
- test/components/narrative.test.js
Adds stats for narrative screen buttons.
> CGPROD-2449_Narrative-Screen-Stats

- CHANGELOG.md
- src/core/debug/debug.js
- src/core/debug/layout-debug-draw.js
- src/core/debug/measure/elements.js
- src/core/debug/measure/get-input-fn.js
- src/core/debug/measure/get-input.js
- src/core/debug/measure/measure.js
- src/core/debug/measure/ui.js
- src/core/debug/measure/update-rect.js
- test/core/debug/debug.test.js
- test/core/debug/layout-debug-draw.test.js
- test/core/debug/measure/get-input-fn.test.js
- test/core/debug/measure/ui.test.js
- test/core/debug/measure/update-rect.test.js
- test/mock/measure.test.js
- themes/default/config/home.json5
* Adds a measuring tool to debug mode
> Noticket debug measure

- CHANGELOG.md
- src/components/narrative.js
- src/components/overlays/pause.js
- src/core/layout/gel-defaults.js
- test/components/narrative.test.js
- test/components/overlays/pause.test.js
- test/core/background/pages.test.js
- test/core/layout/gel-defaults.test.js
* Skip narrative audio when leaving the narrative screen via an overlay
* Add achievements button to pause page.
> CPROD 2508 & 2454 Audio Skip / Achievements on Pause

- CHANGELOG.md
- src/components/overlays/pause.js
- test/components/overlays/pause.test.js
Don't show level select button if already on level select
> Cgprod 2458 level select

- src/core/debug/debug.js
- src/core/debug/measure/elements.js
- src/core/debug/measure/get-input-fn.js
- src/core/debug/measure/measure.js
- src/core/debug/measure/mode.js
- src/core/debug/measure/mode.test.js
- src/core/debug/measure/ui.js
- test/core/debug/debug.test.js
- test/core/debug/measure/get-input-fn.test.js
- test/core/debug/measure/mode.test.js
- test/core/debug/measure/ui.test.js
- test/mock/measure.test.js
* Adds different coordinate modes.
* Change shift and crtrl to z and x due to Mac oddness
> Noticket measure addition

- src/components/game.js
- src/components/results/results-screen.js
- src/components/results/results-stats.js
- test/components/results/results-stats.test.js
- test/game.test.js
also fix gameComplete getting thrown into stats
> [CGPROD-2514] Fix missing level in score stat

- CHANGELOG.md
- src/core/states.js
- test/core/states.test.js
* Set default value of null for state  (undefined cannot be serialised to local storage)
> CGPROD 2535 State Storage

- src/core/scaler.js
- test/core/scaler.test.js
to see whether this fixes scaling on an iPad 4th Gen... also known as the 2012 iPad on iOS 10.
> [CGPROD-2532] Test adding onorientationchange event to scaler

- CHANGELOG.md
- build-scripts/webpack.config.js
- dev/scripts/dynamicScripts.js
- src/core/loader/phaser-defaults/base-defaults.js
- test/core/loader/phaser-defaults/get-base-defaults.test.js
- test/core/loader/phaser-defaults/get-phaser-defaults.test.js
- test/core/startup.test.js
* Adds job name and build number to Phaser banner
> NOTICKET build banner

- CHANGELOG.md
- src/core/layout/gel-defaults.js
- test/core/layout/gel-defaults.test.js
Updates the small achievements indicator when the game is unpaused from the results screen.
> CGPROD-2524_Achievement-Notification-Not-Updating

- CHANGELOG.md
- docs/development/select-screen.md
- src/components/select/select-screen.js
- src/core/layout/grid/grid.js
- test/components/select/select-screen.test.js
- test/core/layout/grid/grid.test.js
Adds gelGrid param for showing the page of a choice on load.
Used on select-screen via transientData
```
this.transientData["level-select"].choice = { id: "choice-id" };
```
https://jira.dev.bbc.co.uk/browse/CGPROD-2522
> CGPROD-2522 gelGrid param for showing select page

- CHANGELOG.md
- docs/UPGRADE-NOTES.md
- src/core/debug/launcher.js
- src/core/layout/gel-button.js
- src/core/layout/gel-group.js
- src/core/layout/layout.js
- test/core/layout/gel-button.test.js
- test/core/layout/gel-group.test.js
- test/core/layout/layout.test.js
* Sets scrollFactor to zero on gel root / groups / buttons so camera movement is ignored.
* Updates getbounds methods to return correct values.
> NOTICKET Gel scroll factor

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/select/select-screen.js
* Bump Phaser version to 3.24.1
> NOTICKET Phaser 3.24.1

- CHANGELOG.md
- build-scripts/webpack.config.js
- package-lock.json
- package.json
Prevent corejs from being transpiled by Babel
> NOTICKET Corejs config

- README.md
- package-lock.json
- Update links to documentation in README.md
- Remove outdated new version info block from README.md
> [CGPROD-2698] update docs

- src/core/layout/scrollable-list/scrollable-list.js
Managed to introduce a bug while refactoring. _cries in TDD_
> [CGPROD-2763] bugfix- fix scaleButton call

- src/components/shop/shop.js
- src/core/layout/scrollable-list/scrollable-list.js
- src/main.js
- test/components/shop/shop.test.js
- test/core/layout/scrollable-list/scrollable-list.test.js
> Convert to class

- CHANGELOG.md
- debug/assets.json
- debug/examples/shop-demo.json5
- src/core/debug/examples.js
- src/main.js
- test/main.test.js
- Add an example shop screen, accessible when `debug=true`
> [CGPROD-2858] add shop debug screen

- CHANGELOG.md
- src/core/layout/gel-group.js
- test/core/layout/gel-group.test.js
Make non-mobile 4/3 area buttons also move to the edges.
> NOTICKET desktop 4/3 area buttons

- debug/examples/select-1.json5
- debug/examples/select-grid.json5
- Work to move the Select screens to the new collections system had not encompassed changing the relevant debug configs.
- This left us with crash bugs on debug, as Select expects a collection name in config but our debug examples weren't providing it. Added.
-  Removed choices arrays from both configs as we now use the collections system and this was no longer needed.
> [CGPROD-2910] fix select debug crash

- src/components/game.js
Fix collection format passed into .set method
Made game checks strict equals to provent IDE warnings on commit.
> CGPROD-2931 Collection Warning

- src/core/layout/scrollable-list/scrollable-list.js
- test/core/layout/scrollable-list/scrollable-list.test.js
* Fix crash when no elements present in collection
> CGPROD 2929 Scrollable list crash

- src/components/shop/balance-ui.js
- src/components/shop/confirm.js
- src/components/shop/menu-buttons.js
- src/components/shop/menu.js
- src/components/shop/shop-layout.js
- src/components/shop/shop-titles.js
- src/components/shop/shop.js
- test/components/shop/balance-ui.test.js
- test/components/shop/confirm.test.js
- test/components/shop/menu-buttons.test.js
- test/components/shop/menu.test.js
- test/components/shop/shop-layout.test.js
- test/components/shop/shop-titles.test.js
- test/components/shop/shop.test.js
- themes/default/shop/config.json5
* Fix alternating menu on resize
> CGPROD 2930 Resize Issues

- package-lock.json
- src/core/layout/scrollable-list/scrollable-list-buttons.js
- src/core/layout/scrollable-list/scrollable-list-handlers.js
- src/core/layout/scrollable-list/scrollable-list.js
- test/core/layout/scrollable-list/scrollable-list-buttons.test.js
- test/core/layout/scrollable-list/scrollable-list-handlers.test.js
- test/core/layout/scrollable-list/scrollable-list.test.js
accessibilifying the label instead of the gel button works for the position. however, the label does not have input events on it, and the gel button does
> [CGPROD-2922] Fix accessibility in scrollable list

- CHANGELOG.md
- package-lock.json
- package.json
Bump Phaser to fix displaylist bug
> Bump Phaser

- cypress/plugins/index.js
- cypress/support/functions.js
- package.json
-Ability to run theme 1 & theme 2 locally and against deployed test url
-Updated docs
-Changed the way environment variables are called as cypress has its own implementation of this.
> Cgprod 2995 theme2

- debug/examples/shop.json5
- lib/rexninepatchplugin.min.js
- package-lock.json
- package.json
- src/components/shop/background.js
- src/components/shop/confirm.js
- src/components/shop/menu.js
- src/components/shop/shop-layout.js
- src/components/shop/shop.js
- src/core/layout/scrollable-list/backgrounds.js
- src/core/layout/scrollable-list/scrollable-list.js
- src/core/loader/phaser-defaults/get-default-plugins.js
- test/components/shop/background.test.js
- test/components/shop/confirm.test.js
- test/components/shop/shop-layout.test.js
- test/components/shop/shop.test.js
- test/core/layout/scrollable-list/backgrounds.test.js
- test/core/layout/scrollable-list/scrollable-list.test.js
- test/core/loader/phaser-defaults/get-default-plugins.test.js
- themes/default/shop/config.json5
* Adds NinePatch plugin
* Adds ninepatch config support to scrollable list
* Update core-js polyfills to latest
> CGPROD 3000 NinePatch

- src/components/game.js
- src/core/layout/scrollable-list/scrollable-list-buttons.js
- src/main.js
- test/components/shop/transact.test.js
- test/game.test.js
- Adds a button to game.js that launches the shop as an overlay
> [CGPROD-2947] part 2 - add overlay shop to main.js

- src/components/shop/confirm.js
- src/components/shop/menu-buttons.js
- test/components/shop/menu-buttons.test.js
Refactor out container when only container.scene is used.
> minor refactor

- package-lock.json
- src/components/shop/scrollable-list/scrollable-list-buttons.js
- test/components/shop/scrollable-list/scrollable-list-buttons.test.js
Set button.off for `disabled` button states, determined by `disabled` prop
in the shop button config.
This stops audio being played for locked buttons, or any button state which has `disabled` in the shop config.
> CGPROD-3095 Scrollable-list button disabled state 

- babel.config.js
- build-scripts/webpack.config.js
- package-lock.json
- src/components/select/select-screen.js
- src/core/layout/grid/cell.js
- src/core/layout/grid/grid.js
- src/core/safari-audio.js
- test/components/select/select-screen.test.js
- test/components/select/single-item-mode.test.js
- test/core/debug/measure/mode.test.js
- test/core/layout/gel-indicator.test.js
- test/core/layout/grid/cell.test.js
- test/core/layout/grid/grid.test.js
- test/game.test.js
* Enable Babel loose transformations to speed up transpiled code (fixes some issues on Chrome)
* Fix an issue in grids where id should be used instead of key
* Fix loops which used [...Array(n)] format _(these do not work correctly with Babel's loose transpilation mode. Look into babel assumptions if we need to correct this in the future: https://babeljs.io/blog/2021/02/22/7.13.0 )_
> NOTICKET Babel Optimisations

- debug/examples/shop-consumables-list.json5
- debug/examples/shop-equippables-list.json5
- src/components/shop/scrollable-list/scrollable-list-buttons.js
- test/components/shop/scrollable-list/scrollable-list-buttons.test.js
- themes/default/shop-list/config.json5
Fixes long description instead of subtitle being used in lists
> Noticket fix subtitle length

- CHANGELOG.md
- package-lock.json
- package.json
Genie 3.9.0 Yoshi's Wooly World
> Release 3.9.0

- package-lock.json
- package.json
* Update webpack cli
* Use new devserver syntax in `start:pack` script
> NOTICKET start:pack update

- cypress/integration/genie_spec.js
- cypress/integration/screenshot_spec.js
- cypress/support/commands.js
- cypress/support/functions.js
- package-lock.json
- package.json
- src/core/debug/debug-screens.js
- src/core/debug/launcher.js
- test/core/debug/launcher.test.js
> [CGPROD-3199] Fix screenshot/genie cypress tests

- cypress/integration/regression/user-action-stat_spec.js
- cypress/integration/shop_spec.js
- cypress/support/statConfig.js
-re-enable cypress tests for shop
-update stats for shop to align with previous work
> Cypress shop updates

- package.json
- src/components/results/results-screen.js
- test/components/results/results-screen.test.js
createTitles is called by layout, so not required in the screen.
> CGPROD-2987 Remove createTitles

- cypress/integration/regression/page-view-stat_spec.js
- cypress/integration/regression/user-action-stat_spec.js
- package-lock.json
- package.json
> stat test refactor

- CHANGELOG.md
- package-lock.json
- package.json
* Fix security issue with webpack dev server
> NOTICKET dependabot fixes

- src/core/gmi/gmi.js
Refactor of setGmi for legibility
> Noticket gmi cleanup

- src/components/home.js
- test/components/home.test.js
* Make home page respect showExitButton from GMI
> CGPROD 3424 Respect Exit

- CHANGELOG.md
- babel.config.js
- test/core/loader/font-loader/font-file.test.js
* Remove IE11
* Set Safari to v10
> Update Babel Targets

- CHANGELOG.md
- build-scripts/webpack.config.js
- package-lock.json
- package.json
Fix for `npm run start:pack` due to outdated webpack config.
> start:pack fix

- CHANGELOG.md
- docs/development/narrative-screen.md
- docs/development/select-screen.md
- docs/development/shop-component/adding-shop.md
- package-lock.json
- package.json
- src/core/loader/boot.js
- src/main.js
- test/core/loader/boot.test.js
Allows to configure different default screen from the home.
> CGPROD-3752 added config option for default home screen

- cypress/integration/select_spec.js
- src/components/select/select-screen.js
- src/core/collections.js
- src/core/layout/grid/grid.js
- test/components/select/select-screen.test.js
- test/core/collections.test.js
- test/core/layout/grid/grid.test.js
Ticket: https://jira.dev.bbc.co.uk/browse/CGPROD-3889
> [CGPROD-3889] level select

- CHANGELOG.md
- docs/development/collections.md
- docs/development/select-screen.md
- package.json
- src/components/game.js
- src/components/select/select-screen.js
- src/core/collections.js
- src/core/layout/gel-defaults.js
- test/components/select/select-screen.test.js
- test/core/collections.test.js
- test/core/layout/gel-defaults.test.js
- test/game.test.js
- remove transient data for selections stored in local storage
- update failing tests
- add test for `getUnique`
> [CGPROD-3889] remove transient data for selections

- src/core/debug/examples.js
- src/core/debug/launcher.js
- test/core/debug/launcher.test.js
Resolves [CGPROD-3984](https://jira.dev.bbc.co.uk/browse/CGPROD-3984)
This branch branches off [Nick's Basisu branch!!](https://jira.dev.bbc.co.uk/browse/CGPROD-3947)
Added the arrows
> Added pagination to Debug page - CGPROD-3984

- CHANGELOG.md
- package.json
- src/core/loader/loader.js
- test/core/loader/loader.test.js
- themes/default/config.json
Makes loader config `loadingBarYPos` optional
Updated package version.
> NOTICKET - loading bar y pos

- CHANGELOG.md
- package.json
- src/core/layout/gel-defaults.js
- test/core/layout/gel-defaults.test.js
Fix crash if no levels collection defined
> NOTICKET Handle No Level Collection

- CHANGELOG.md
- package-lock.json
- package.json
- test/mock/mock-scene.js
Bumped to 3.70
Tested all screens and debug screens
> Phaser 3.70 bump

- CHANGELOG.md
- src/core/debug/launcher.js
- test/core/debug/launcher.test.js
https://jira.dev.bbc.co.uk/browse/CGPROD-4040
> [CGPROD-4040] call ShowCurrentPage after adding screens

- CHANGELOG.md
- build-scripts/webpack.config.js
- package-lock.json
- package.json
- src/components/shop/scrollable-list/scrollable-list-covers.js
- src/core/debug/debug.js
- src/core/layout/gel-group.js
* Update webpack config
* Update versions for point release
> CGPROD 3982 Start Pack
