src/core/loader/loader.js
test/core/loader/loader.test.js

Progress bar update method moves backwards as assets are added to the
loader queue after progress is updated. Total assets in queue increases
faster than they are loaded.
This is a dirty fix to only increase the progress bar if the percentage
increases. This will add inaccuracy (slow phase) to the lower end of the
bar but will fix any backwards movement.
[|||.........................]
[|||||.......................]
[||||||||....................]
[||||||......................]
[||||........................]
[|||||||||...................]
[||||||||||||||.............]
[||||||||||||||||||.........]
[||||||||||||||||||||.......]
[|||||||||||||||||||||||....]
[|||||||||||||||||||||||||||]

CGPROD-2124 Dirty fix for progress bar progress

---

src/components/overlays/pause.js
src/core/layout/gel-defaults.js

- Fixes order of play / replay _(play should be on the right)_
- Fixes draw order of title and buttons _(buttons should be on top)_

Cgprod 2082 button order

---

src/core/layout/grid/cell.js
test/core/layout/grid/cell.test.js

Calculation for blank cells was incorrect. Fixed to actually return the
number of blank cells, and taken out the 0.5 multiplier into the
alignment calculation.
https://jira.dev.bbc.co.uk/browse/CGPROD-2217

CGPROD-2217 Select screen cell alignment fix

---

src/components/select/add-events.js
src/core/layout/grid/grid.js
test/core/layout/grid/grid.test.js

Clicking continue does not pass a callback returning the same object as when clicking the gel button, this meant that selection.title was undefined when pressing continue. 
To fix this we now pass the currently selected button's title and id via a callback into the next function on select screen.

CGPROD-2231: Undefined Stat for Single Item Select Screen

---

src/core/layout/gel-button.js
test/core/layout/gel-button.test.js

Prevents Gel Buttons audio from being paused.
The Pause overlay calls pauseAll. This causes audio triggered before opening the overlay to pause which was causing this bug.
PR sets up a callback to run once a pause event is called on the button, which then resumes the button click audio.

CGPROD-2211: Pause Button Audio Bug

---

CHANGELOG.md
src/core/screen.js
test/core/screen.test.js

Pause, settings, how to play and achievements overlays should not set
stat screen so that the stats placement entry reports the page which
called it.
https://jira.dev.bbc.co.uk/browse/CGPROD-2228

CGPROD-2228 Stop stats screen being set by overlay

---

src/core/screen.js
test/core/screen.test.js

Class call of setStatsScreen should be used on overlay close, rather
than ditrectly GMI. This fixes chained overlays from changing the stats
screen when their 'child' overlay is closed.
https://jira.dev.bbc.co.uk/browse/CGPROD-2228

CGPROD-2228 Close overlay use class call of stats

---

CHANGELOG.md
src/core/startup.js
test/core/startup.test.js

Disable Phaser window events to prevent clickthrough on achievements / settings

Cgprod 2240 window events

---

debug/examples/select-grid.json5

Clarifies rows and columns
(was previously x and y which is written reversed to rows and columns)

NOTICKET - Clarifies rows and columns

---

themes/default/gel/gel-pack.json

Fixes small achievement size button in desktop.
NB: theme 2 is currently broken in multiple ways andd will need looking at.

Noticket small desktop achievements button.

---

CHANGELOG.md
src/components/select/select-screen.js
src/components/select/single-item-mode.js
src/components/select/titles.js
test/components/select/select-screen.test.js
test/components/select/single-item-mode.test.js
test/components/select/titles.test.js

* Select screen uses configured storageKey instead of "levels" hardcoded.

NOTICKET Select Fix

---

dev/scripts/gmi.js
docs/development/achievements.md

Put achievements logging behind the debug flag as pollutes the console log in local development.

NOTICKET achievements debug

---

package-lock.json
src/components/select/select-screen.js
test/components/select/select-screen.test.js

Allows particle effects to hook into the pointerover/out events.
Makes way for allowing separate particle emitter config for the items "disabled" state on pointerover/out.

[CGPROD-2396] Enable pointerover/out events on disabled select items

---

src/core/debug/debug.js
src/core/layout/gel-defaults.js
test/core/debug/debug.test.js

This allows for testing of screen based data and functions in the
workflow, when in debug mode.
- expose screen on window.__debug.screen
- fix asset key for 'Play again' button

CDPROD-2045 Expose screen in debug mode

---

CHANGELOG.md
src/components/select/select-particles.js
test/components/select/select-particles.test.js

Disabled buttons already have their POINTER_UP listeners removed - hence there is a listener count is 0 check.

[CGPROD-2402] Remove particle emitters on disabled select screen buttons

---

CHANGELOG.md
src/core/layout/gel-defaults.js
test/core/layout/gel-defaults.test.js

Adds param to stat for the level select button on pause screen which
contains level ID.
https://jira.dev.bbc.co.uk/browse/CGPROD-2459

CGPROD-2459 Add source to pause level select btn

---

CHANGELOG.md
src/core/accessibility/accessible-dom-element.js
test/core/accessibility/accessible-dom-element.test.js

Add empty touchstart event listener to accessible dom elements so ios voiceover double tap works.

Cgprod 2465 voice blocker

---

CHANGELOG.md
src/core/screen.js
test/core/screen.test.js

* Removes the code that stopped overlays calling set stats screen because it is now needed.

NOTICKET overlay stats screen

---

CHANGELOG.md
src/core/layout/gel-defaults.js
test/core/layout/gel-defaults.test.js

Prevents duplicate stat firing on Narrative screen "skip" button.

 CGPROD-2516_Narrative-skip-button-duplicate-click 

---

CHANGELOG.md
src/core/states.js
test/core/states.test.js

* Force states to always serialise to an Object (fp.set will serialise to an array if numeric keys are used)

NOTICKET State serialisation

---

CHANGELOG.md
src/core/layout/gel-defaults.js
test/core/layout/gel-defaults.test.js

already done in CAGE on `gmi.exit()`

[CGPROD-2615] Remove exit stat being fired

---

docs/development/achievements.md
themes/default/achievements/config.json5

- Updated `achievements.md` - remove redundant instruction on enabling achievements, clearer guidance on renaming / reordering achievements
- Updated `themes/default/achievements/config.json5` - explanatory comments, prefix strings CHANGE_THESE_STRINGS for clarity

[CGPROD-2701] nudge devs towards achievement variety

---

debug/examples/results-conditional-assets.json5

- We were crashing when passing a negative `keys` value and displaying a green box on a negative `stars` value
- Clamped the ranges passed from transientData so `stars` is in the range 0-3 and `keys` is in the range 0-1

[CGPROD-2708] Bug fix- range clamp for conditional asset picking from transientData

---

src/core/debug/launcher.js
test/core/debug/launcher.test.js

- `window.prompt()` we added to parameterise the conditional assets screen steals focus in a browser-dependent way
- so, prevent the audio engine pausing on blur.

[CGPROD-2708] fix silent audio on conditional assets debug screen

---

src/core/layout/gel-button.js
test/core/layout/gel-button.test.js

- GEL buttons now check that frame 1 exists before trying to set their sprite to frame 1
- Added unit test

[CGPROD-2720] fix error spam on missing hover states for GEL buttons

---

CHANGELOG.md
package-lock.json
src/core/accessibility/accessible-dom-element.js
test/core/accessibility/accessible-dom-element.test.js

The how to play screen has that "accessible carousel" thing that has a weird screen reader only div on it that reads out what page you are on. It doesn't have a click event on it so it crashes.

[CGPROD-2802] Fix crash on pressing enter key on how to play screen

---

CHANGELOG.md
src/components/home.js
src/core/debug/debug.js
src/core/debug/safe-area-draw.js
src/core/layout/safe-area.js
src/main.js
test/core/debug/debug.test.js
test/core/debug/safe-area-draw.test.js
test/core/layout/safe-area.test.js
themes/default/home/config.json5

- Provides a new key ('U') in debug mode that shows the safe area
- Adds `safe-area-draw.js` to get and draw this safe area
- Adds a new param `mirrorY` to `scene.layout.getSafeArea()`, defaulting to true, which has the safe area vertically centred (the way we want it in Select) 
- Uses mirrorY = false when getting the safe area for debug mode

[CGPROD-2797] safe area debug

---

CHANGELOG.md
src/core/layout/gel-group.js
test/core/layout/gel-group.test.js

* Buttons within the 4/3 area now sit exactly on the edge in mobile breakpoint.
* Buttons will move inwards if the screen width causes the border pad to overlap the 4/3 area.
Mobile mode wide:
Mobile mode 4/3:
Old mobile mode:

CGPROD 2850 4/3 Area buttons

---

src/core/layout/scrollable-list/scrollable-list.js

- in post-flight on CGPROD-2674 it was noted that the scrollable list was not conforming to the edges of the safe area
- in a previous UX chat we noted X- and Y-axis padding values should be different to conform to the UX spec
- following the change we were not conforming because we were using a Y where we should have used an X.
- fixed.

[CGPROD-2674] fix resize being a couple of px off

---

src/main.js
test/main.test.js

- Previous PR on this ticket broke all the asset paths as they relied on the shop existing in the theme and main.js
- Ideally we'd have all debug assets under the debug assets folder. however:
- gel buttons depend on a dot-separated asset path
- debug mode depends on underscore-separated paths
- hilarity ensues
- as a quick fix, add Shop back to main.js

[CGPROD-2858] shop debug screen - unbreak asset paths, the fast way

---

src/components/game.js
test/game.test.js

some reason there's a callback on both the continue text and the image and they were both firing navigate to the results screen events at the same time.

[CGPROD-2900] Remove extra navigate callback

---

src/components/shop/transact.js
test/components/shop/transact.test.js

- Mostly, just reuses existing functions created for the shop confirm screen
- Adds an equip transaction
- Does not visually update anything (this will be done in CGPROD-2928) but we can verify: dev tools => application => local storage => check state of local storage before & after the transaction.

[CGPROD-2769] equip confirm screen

---

src/components/shop/shop.js
src/core/layout/scrollable-list/scrollable-list.js
test/core/layout/scrollable-list/scrollable-list.test.js

- We had some situations where resizing the scrolly list would break the layout
- turns out that as well as a resize subscription, we also needed to add to onScaleChange

[CGPROD-2913] fix resize of scrollable list

---

src/components/shop/menu-buttons.js
src/core/layout/scrollable-list/scrollable-list-buttons.js
test/components/shop/menu-buttons.test.js
test/core/layout/scrollable-list/scrollable-list-buttons.test.js

- Various buttons in the shop were lacking an unsubscribe on shutdown
- This meant that after the first launch of the shop in a given session, the event bus had two callbacks for each click, one of which would have a null pointer and therefore cause a crash.
- Added unsubscribe on shutdown via `scene.events.once`

[CGPROD-2911] fix crashy click handlers

---

src/components/game.js
test/game.test.js

- Button text was interactive, as was the button graphic itself, resulting in duplicate clicks.
- Removed the `onPointerUp` event from the text elem
- Also removed a redundant `setInteractive`
- Update tests

[CGPROD-2915-b] Fix duplicate button click in demo game

---

src/core/debug/launcher.js

- Debug launcher filters out screens from examples.js that have a property `hidden: true`
- These screens are still available to route to, so we can now build more complex flows inside debug.

[CGPROD-2844] Allow debug screens to be hidden

---

debug/examples/shop.json5
src/components/shop/balance-ui.js
src/components/shop/shop.js
src/components/shop/transact.js
src/core/layout/scrollable-list/scrollable-list.js
test/components/shop/balance-ui.test.js
test/components/shop/shop.test.js
test/components/shop/transact.test.js
test/core/layout/scrollable-list/scrollable-list.test.js
themes/default/items/game-items.json5
themes/default/items/inventory.json5

- relevant code now uses the quantity of a nominated inventory item as currency
- currency item is filtered out of the scrollable list
- transactions update the quantity of that nominated item in the inventory collection
- panel updating checks against the filtered collection

[CGPROD-2844] use currency from inventory

---

src/components/shop/confirm.js
src/components/shop/menu-buttons.js
test/components/shop/confirm.test.js
test/components/shop/menu-buttons.test.js

- x position of shop menu buttons was being calculated wrong- fixed
- x-position for confirm price icon, text and prompt were not being flipped on `buttonsRight : false` - fixed.

[CGPROD-2962] fix buttonsRight config

---

src/components/shop/shop.js
test/components/shop/shop.test.js

- Add a11y.reset call on changing panes, update tests.
- Tested with keyboard tabbing and VoiceOver
- some oddness with highlighting on VoiceOver, but this appears to be coming from the rexUI plugin- may not be in our gift to fix. However, the voiceover is consistent with our other pages, and tabbing definitely works nicely.

[CGPROD-2981] fix tab order on shop pane navigation 

---

src/core/layout/scrollable-list/scrollable-list.js
test/core/layout/scrollable-list/scrollable-list.test.js

- To get resize working nicely scrollable-list needed to be resized twice- once by the scaler (`onScaleChange.add()`) and once by Phaser (`scene.events.on("resize", [fn])`) - this resolved an issue with RexUI not playing nicely with our scaler.
- We weren't removing the scene.events.on listener, resulting in an NPE on resize once the user had visited the shop.
- Added a shutdown listener that unsubs from the Phaser event, resolving the NPE.
- Add test.

[CGPROD-2978] fix resize crash after using a screen with a scrollable list

---

src/core/collections.js
src/core/debug/debug-mode.js
src/core/debug/debug-screens.js
src/core/loader/load-collections.js
src/core/loader/loader.js
test/core/collections.test.js
test/core/debug/debug-mode.test.js
test/core/debug/debug-screens.test.js
test/core/loader/load-collections.test.js

* Fix the pathing issue.
* Also add `debug=nolog` option to remove loader log that only QA use

NOTICKET debug collection Fixes

---

src/core/layout/scrollable-list/scrollable-list-handlers.js
test/core/layout/scrollable-list/scrollable-list-handlers.test.js

- Like other buttons in genie, scrollable list buttons are GEL buttons, and are a synthesis of DOM elements and interactive Phaser elements
- Since the scrollable list builds inner elements first, GEL buttons may be live in the DOM before the scrollable list has finished construction
- We were seeing rare, hard to reproduce crashes on calls to `gelButton.rexContainer.parent.getTopmostSizer()` which were _probably_ caused in this way
- Added a guard if `parent` (i.e. the scrollable list) does not yet exist, and a test to document
- This should be fine as any event hitting this time window ought to be happening before the list is visible to the user (i.e. we can assume it was not an intentional click.)

[CGPROD-3012] guard vs race condition on getTopmostSizer 

---

debug/examples/shop-demo-shop.json5
debug/examples/shop.json5
src/components/shop/balance-ui.js
src/components/shop/confirm.js
src/components/shop/menu-buttons.js
src/components/shop/shop-layout.js
src/components/shop/shop-titles.js
src/core/layout/scrollable-list/button-overlays.js
test/components/shop/balance-ui.test.js
test/components/shop/confirm.test.js
test/components/shop/shop-layout.test.js
test/core/layout/scrollable-list/button-overlays.test.js

- DRY style merging with new fn on shop-layout (mostly, to force consistency)
- Update scene.add.text() calls to use new styling fn
- Modify confirm.js to create three text fields in item detail view, rather than 2
- Update shop config to reflect & exemplify changes
- Strip explanatory comments from the demo game shop config, since they were duplicates.

[CGPPROD-2963] improve shop item information architecture and rationalise config

---

src/core/layout/scrollable-list/scrollable-list-handlers.js
src/core/layout/scrollable-list/scrollable-list.js
test/core/layout/scrollable-list/scrollable-list-handlers.test.js
test/core/layout/scrollable-list/scrollable-list.test.js

- modified mousewheel handler to sub to the more specific and useful `gameobjectwheel` event
- prevent propagation, fixing full-screen 'bounce' effect on some browsers
- removed hard-coded `WHEEL_SCROLL_FACTOR` as it was giving us very variable results dependent on framerate and client
- added `wheelScrollFactor` fn that returns a scroll factor that's inversely proportional to the size of the list - this should give us a more consistent scroll rate.
- clamped `getMaxOffset` to a zero lower limit (so a list that's smaller than the pane has a zero max offset.)
- guard against setting t on the list when it hasn't changed (for efficiency- setting t kicks off a bunch of other code.)

[CGPROD-3013] part deux- refine scroll wheel behaviour

---

src/core/safari-audio.js
src/core/startup.js
test/core/safari-audio.test.js
test/core/startup.test.js

Fixes audio in Safari after using a prompt in the debug screen.
This may also fix a previous iOS bug that I remember. That one prevented audio from playing after switching safari tabs or changing app to a different app in iOS.

[CGPROD-3043] Fixes web audio on safari being stuck in the interrupted state.

---

src/components/shop/menu-buttons.js
src/components/shop/shop.js
src/components/shop/transact.js
test/components/shop/menu-buttons.test.js
test/components/shop/shop.test.js
test/components/shop/transact.test.js

- fires a `'shopmenu'` stat on create()
- Menu button callbacks fire `'shopbuy'` and `'shopmanage'` page view stats
- shop.back() fires a stat if the target pane is the top menu
- all transactions fire item action stats
- refactor transact.test.js to be more DRY

[CGPROD-2812] shop stats

---

CHANGELOG.md
src/main.js

fixes pause bug when checking for `restart` and `select` routes.

GGPROD-3073 Added routes for shop navigation

---

src/components/shop/scrollable-list/scrollable-panel.js
test/components/shop/scrollable-list/scrollable-panel.test.js

Add getBoundingRect to scrollable list.
(Required to show bounding rect on "W" key in debug mode now it is used as a custom group.)

CGPROD 3115 - W key crash

---

CHANGELOG.md
src/components/shop/menu.js
test/components/shop/menu.test.js

Adds resize for shop menu based on re-calculated bounds.
When resizing the window, the buttons will now better recalculate their correct
size when the bounds have significantly changed.

CGPROD-3129 getRect

---

CHANGELOG.md
src/components/shop/scrollable-list/scrollable-list.js
test/components/shop/scrollable-list/scrollable-list.test.js

Key press was not being recognised when no pointer events had previously been fired, added condition for `keydown` on event to call `showConfirmation`.
- Fixes using the return/space key to navigate to shop confirm screen when only tabbing.
- Fixes some unit tests that were not testing anything.

CGPROD-3128 Fix showing shop confirm on key press

---

CHANGELOG.md
package-lock.json
src/components/shop/scrollable-list/scrollable-list-handlers.js
test/components/shop/scrollable-list/scrollable-list-handlers.test.js

Reposition shop-list accessible elements on scroll and tab events.
Fixes bug CGPROD-3156

CGPROD-3156 Reposition shop-list a11y elements

---

CHANGELOG.md
package-lock.json
package.json
src/core/layout/gel-button.js
src/core/music.js
test/core/layout/gel-button.test.js
test/core/music.test.js

SoundManager can add multiple sounds under the same asset key (allows for different sound configs for the same asset).
So calling `scene.sound.add()` adds an extra sound to the manager each time.
We were calling `scene.sound.add()` on each button in the scene, so after loading the scene multiple times, there were a lot of sounds added, causing the distorted audio.
`.get()` will get the first sound
`.getAll()` would return an array of sounds under that key.
https://photonstorm.github.io/phaser3-docs/Phaser.Sound.WebAudioSoundManager.html#get__anchor

[CGPROD-3238] Fix distorted audio

---

build-scripts/build.sh
package-lock.json
package.json
src/core/debug/dom-text.js

Phaser has merged changes that the apps team need to release, this change makes use of the latest Phaser build
Solves the same problem as: https://github.com/bbc/genie/pull/489, but has significantly less changes.
Because we are just changing the listed dependency now (not configuring webpack or jest anymore) moving to the next scheduled Phaser release in a few weeks will be a one line change.

Make use of the latest Phaser build

---

src/core/browser.js
test/core/browser.test.js

Reusing the same RegExp object was causing it to return a different boolean each time. Couldn't reproduce this behaviour in unit tests though, bit strange.

Fix isKindleWebView from returning different boolean each time

---

cypress/integration/select_spec.js
src/core/collections.js
test/core/collections.test.js

Ticket: https://jira.dev.bbc.co.uk/browse/CGPROD-3889
- update to use catalogue with the local storage items merged into it with `getAll()`
- update relevant unit/integration tests

[CGPROD-3889] level select fix

---

CHANGELOG.md
docs/development/global-config.md
src/core/layout/gel-defaults.js
src/core/layout/gel-group.js
src/core/layout/group-layouts.js
src/core/layout/layout.js
src/core/loader/boot.js
test/core/layout/gel-defaults.test.js
test/core/layout/gel-group.test.js
test/core/layout/group-layouts.test.js
test/core/layout/layout.test.js
themes/default/config.json
themes/default/game-config.json

Ticket: https://jira.dev.bbc.co.uk/browse/CGPROD-3891
- added global `game-config` file with a flag for `verticalTopRight` that loads in in `Boot`
- added `topRightV` group layout option
- fixed offset/positioning of top right buttons when vertical layout is selected
- updated/added relating unit tests

[CGPROD-3891] top right buttons - vertical option

---

CHANGELOG.md
dev/scripts/web-config.js

Disable compression (was causing slow starts for local dev when using unbundled ES6 modules)

CGPROD 3891 Slow local dev startup

---

CHANGELOG.md
docs/development/dom-text.md
package.json
src/core/layout/dom-text.js
test/core/layout/dom-text.test.js

Added `addOuterStroke` method to dom text - automatically adds pseudo element hacks to simulate outer stroke.

NOTICKET Dom Text Outer Stroke
